#include "projection_compositor.h"
#include <algorithm>
#include <cmath>
namespace projection_compositor {
RGB fromHsl(float h,float s,float l){h=h-std::floor(h);const float c=(1.0f-std::abs(2.0f*l-1.0f))*s;const float x=c*(1.0f-std::abs(std::fmod(h*6.0f,2.0f)-1.0f));const float m=l-c*0.5f;RGB out{};const int sector=static_cast<int>(h*6.0f)%6;switch(sector){case 0:out={c,x,0};break;case 1:out={c,c,0};break;case 2:out={0,c,x};break;case 3:out={0,x,c};break;case 4:out={x,0,c};break;default:out={x,0,x};break;}for(float&v:out)v+=m;return out;}
void toHsl(const RGB& rgb,float&h,float&s,float&l){const float mx=std::max({rgb[0],rgb[1],rgb[2]}),mn=std::min({rgb[0],rgb[1],rgb[2]});const float d=mx-mn;l=(mx+mn)*0.5f;s=d<=1e-8f?0.0f:d/(1.0f-std::abs(2.0f*l-1.0f));if(d<=1e-8f)h=0.0f;else if(mx==rgb[0])h=std::fmod((rgb[1]-rgb[2])/d,6.0f)/6.0f;else if(mx==rgb[1])h=((rgb[2]-rgb[0])/d+2.0f)/6.0f;else h=((rgb[0]-rgb[1])/d+4.0f)/6.0f;h-=std::floor(h);}
RGB blendRgb(const RGB& b,const RGB& s,int mode,const float* p){RGB o{};for(int c=0;c<3;++c){const float B=b[c],S=s[c];switch(mode){case 1:o[c]=std::min(B,S);break;case 2:o[c]=std::pow(std::clamp(B*S,0.0f,1.0f),1.0f/std::max(.01f,p[3]));break;case 3:o[c]=S<=1e-8f?0.0f:std::min(std::clamp(1.0f-(1.0f-B)/S,0.0f,1.0f),p[6]);break;case 4:o[c]=std::max(B,S);break;case 5:o[c]=std::pow(std::clamp(1.0f-(1.0f-B)*(1.0f-S),0.0f,1.0f),1.0f/std::max(.01f,p[3]));break;case 6:o[c]=S>=1.0f-1e-8f?std::min(1.0f,p[6]):std::min(std::clamp(B/(1.0f-S),0.0f,1.0f),p[6]);break;case 7:case 9:{const float pivot=std::clamp(p[5],.0001f,.9999f);const float low=B*S/pivot,high=1.0f-(1.0f-B)*(1.0f-S)/(1.0f-pivot);o[c]=(mode==7?B:S)<pivot?low:high;break;}case 8:{const float d=B<=.25f?((16*B-12)*B+4)*B:std::sqrt(std::clamp(B,0.0f,1.0f));const float standard=S<=.5f?B-(1-2*S)*B*(1-B):B+(2*S-1)*(d-B);o[c]=std::clamp(B+(standard-B)*((p[7]-.5f)*2.0f),0.0f,1.0f);break;}case 10:o[c]=std::abs(B-std::clamp(S+p[10],0.0f,1.0f));break;case 11:{const float v=std::clamp(S+p[10],0.0f,1.0f);o[c]=B+v-2*B*v;break;}default:o[c]=S;break;}}if(mode>=12&&mode<=15){float hb,sb,lb,hs,ss,ls;toHsl(b,hb,sb,lb);toHsl(s,hs,ss,ls);hs+=p[8]/360.0f;ss=std::clamp(ss*p[9],0.0f,1.0f);if(mode==12)return fromHsl(hs,sb,lb);if(mode==13)return fromHsl(hb,ss,lb);if(mode==14)return fromHsl(hs,ss,lb);return fromHsl(hb,sb,ls);}return o;}
Pixel candidate(const Pixel& backdrop,const RGB& source,float sourceA,int mode,const float* params){const RGB blend=blendRgb(backdrop.rgb,source,mode,params);Pixel out;out.a=sourceA+backdrop.a*(1.0f-sourceA);if(out.a<=1e-8f)return out;for(int c=0;c<3;++c){const float premul=source[c]*sourceA*(1.0f-backdrop.a)+blend[c]*(sourceA*backdrop.a)+backdrop.rgb[c]*backdrop.a*(1.0f-sourceA);out.rgb[c]=premul/out.a;}return out;}
int opposite(int mode){switch(mode){case 2:return 5;case 5:return 2;case 7:return 9;case 9:return 7;case 3:return 6;case 6:return 3;case 12:return 15;case 15:return 12;default:return -1;}}
void compose_layer(Pixel& acc,const RGB& src,float sa,int mode,const float* params,int oppositeMode,const float* weights,float total){if(total<=0)return;Pixel main{},normal{},other{};if(mode==0){normal=candidate(acc,src,sa,0,params);main=other=normal;}else{if(weights[0]>0)main=candidate(acc,src,sa,mode,params);if(weights[1]>0)normal=candidate(acc,src,sa,0,params);if(oppositeMode>=0&&weights[2]>0)other=candidate(acc,src,sa,oppositeMode,params);}const float outA=(main.a*weights[0]+normal.a*weights[1]+(oppositeMode>=0?other.a*weights[2]:0))/total;RGB premul{};for(int c=0;c<3;++c)premul[c]=(main.rgb[c]*main.a*weights[0]+normal.rgb[c]*normal.a*weights[1]+(oppositeMode>=0?other.rgb[c]*other.a*weights[2]:0))/total;acc.a=outA;for(int c=0;c<3;++c)acc.rgb[c]=outA>1e-8f?premul[c]/outA:0;}
}
