# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.4

# Delete rule output on recipe failure.
.DELETE_ON_ERROR:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/deanos/Documents/CreativeSystem v0.1"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/deanos/Documents/CreativeSystem v0.1/build_cpp"

# Utility rule file for CreativeCore_autogen.

# Include any custom commands dependencies for this target.
include CMakeFiles/CreativeCore_autogen.dir/compiler_depend.make

# Include the progress variables for this target.
include CMakeFiles/CreativeCore_autogen.dir/progress.make

CMakeFiles/CreativeCore_autogen: CreativeCore_autogen/timestamp

CreativeCore_autogen/timestamp: /usr/lib/qt6/moc
CreativeCore_autogen/timestamp: CMakeFiles/CreativeCore_autogen.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --blue --bold --progress-dir="/home/deanos/Documents/CreativeSystem v0.1/build_cpp/CMakeFiles" --progress-num=$(CMAKE_PROGRESS_1) "Automatic MOC and UIC for target CreativeCore"
	/usr/bin/cmake -E cmake_autogen "/home/deanos/Documents/CreativeSystem v0.1/build_cpp/CMakeFiles/CreativeCore_autogen.dir/AutogenInfo.json" ""
	/usr/bin/cmake -E touch "/home/deanos/Documents/CreativeSystem v0.1/build_cpp/CreativeCore_autogen/timestamp"

CMakeFiles/CreativeCore_autogen.dir/codegen:
.PHONY : CMakeFiles/CreativeCore_autogen.dir/codegen

CreativeCore_autogen: CMakeFiles/CreativeCore_autogen
CreativeCore_autogen: CreativeCore_autogen/timestamp
CreativeCore_autogen: CMakeFiles/CreativeCore_autogen.dir/build.make
.PHONY : CreativeCore_autogen

# Rule to build all files generated by this target.
CMakeFiles/CreativeCore_autogen.dir/build: CreativeCore_autogen
.PHONY : CMakeFiles/CreativeCore_autogen.dir/build

CMakeFiles/CreativeCore_autogen.dir/clean:
	$(CMAKE_COMMAND) -P CMakeFiles/CreativeCore_autogen.dir/cmake_clean.cmake
.PHONY : CMakeFiles/CreativeCore_autogen.dir/clean

CMakeFiles/CreativeCore_autogen.dir/depend:
	cd "/home/deanos/Documents/CreativeSystem v0.1/build_cpp" && $(CMAKE_COMMAND) -E cmake_depends "Unix Makefiles" "/home/deanos/Documents/CreativeSystem v0.1" "/home/deanos/Documents/CreativeSystem v0.1" "/home/deanos/Documents/CreativeSystem v0.1/build_cpp" "/home/deanos/Documents/CreativeSystem v0.1/build_cpp" "/home/deanos/Documents/CreativeSystem v0.1/build_cpp/CMakeFiles/CreativeCore_autogen.dir/DependInfo.cmake" "--color=$(COLOR)" CreativeCore_autogen
.PHONY : CMakeFiles/CreativeCore_autogen.dir/depend

